# Generated by Django 4.2.20 on 2025-05-09 17:44

from django.db import IntegrityError, migrations, models

from NEMO import migrations_utils


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0112_fix_project_name_uniqueness"),
    ]

    def prevent_usage_events_and_area_access_duplicates(apps, schema_editor):
        UsageEvent = apps.get_model("NEMO", "UsageEvent")
        # Check for duplicates (same tool and end date)
        duplicates = UsageEvent.objects.values("tool", "end").annotate(count=models.Count("id")).filter(count__gt=1)
        if duplicates.exists():
            duplicate_details = "\n".join(f"Tool: {item['tool']}, End: {item['end']}" for item in duplicates)
            raise IntegrityError(
                f"Migration aborted! Duplicate UsageEvents found with the same tool and end date: \n{duplicate_details}"
            )
        AreaAccessRecord = apps.get_model("NEMO", "AreaAccessRecord")
        # Check for duplicates (same area, user and end date)
        duplicates = (
            AreaAccessRecord.objects.values("area", "customer", "end")
            .annotate(count=models.Count("id"))
            .filter(count__gt=1)
        )
        if duplicates.exists():
            duplicate_details = "\n".join(
                f"Area: {item['area']}, User: {item['customer']}, End: {item['end']}" for item in duplicates
            )
            raise IntegrityError(
                f"Migration aborted! Duplicate AreaAccessRecords found with the same area, user and end date: \n{duplicate_details}"
            )

    operations = [
        migrations.RunPython(prevent_usage_events_and_area_access_duplicates, migrations.RunPython.noop),
        migrations.RunPython(
            migrations_utils.news_for_version_forward("7.2.0"), migrations_utils.news_for_version_reverse("7.2.0")
        ),
    ]
